#!/bin/bash -e

#example 1

XVAR="123"
YVAR="abc def"
ZVAR=$YVAR
AVAR="${XVAR}${YVAR} 123456"
XVAR="666"
YVAR="xxx 111 333"
echo "$XVAR $XVAR"
echo $ZVAR
echo $AVAR
#>>>>>>>>>>>>>>>>>>
#echo "${XVAR}-${YVAR} 123456"

ls -1 /
ls -1 /|grep usr

LSVAR=$(ls ${HOME}/Desktop)

#------------------------
#echo "123 LSVAR=$LSVAR"
LSVAR="$(ls /) $(ls /home)"
echo "$LSVAR"

PROCSUBVAR="--------->>>>>>>>"
PROCSUBVAR="${PROCSUBVAR}$(ls -1 /home) $(ls -1 /usr)"
#PROCSUBVAR="--------->>>>>>>>$(ls /home) $(ls /usr)<<<<<<<---------"
echo "$PROCSUBVAR"
PROCSUBVAR=$XVAR
echo $PROCSUBVAR