#!/bin/bash

cnt=0

while [[ $cnt -lt 10 ]];do cnt=$(( cnt + 1 ));echo $cnt $((cnt + 1 ));done

SCALL=$(ls -1 /tmp)
echo "retcode from ls -1 /tmp=$?"

ls -1 /tmpx

echo "bad retcode=$?"

HASTACK="100abc:::"
PART="ABBA"
FIND="abc"
echo $HASTACK
#NEEDLE=${HASTACK//"abc"/"--"}
NEEDLE="${HASTACK//$FIND/"--"}"

echo $NEEDLE