#!/bin/bash

if [[ 1 -ge 1 ]]; then
	cnt=0
	while [[ $cnt -lt 100 ]]; do
		file="/home/keithhedger/Backgrounds"
		echo $file
		while read; do
			echo "$REPLY"
			echo ${REPLY%.*}
			basename $REPLY .png
		done < <(ls -1 $file | sort -r)

		file="/home/keithhedger/Wallpapers"
		echo $file
		while read filename; do
			echo "$filename"
			#echo ${filename%.*}
			#basename $filename .png
		done < <(find $file)
		cnt=$((cnt + 1))
	done
else
	cnt=0
	file="/home/keithhedger/Backgrounds"
	while [[ $cnt -lt 10 ]]; do
		data=$(find /media/MediaStore/Music/Mp3s/Music)
		data=$(ls -1 $file | sort -r)
		data=$(find /media/MediaStore/Music/Flacs/Music)
		cnt=$((cnt + 1))
	done
fi
