#!/bin/bash -e

#echo always preserves whitespace ( for now! )

aaaa="ababa"
bbb="cacacac"
qqq="wawawa"

PROCSUBVAR="aaaa"
PROCSUBVAR="$aaaa"
PROCSUBVAR="${aaaa}"
PROCSUBVAR="aaa${aaaa}ddd"
PROCSUBVAR="${aaaa}ddd $bbb         XXXX$qqq"

echo $PROCSUBVAR

