#!/bin/bash -e

#©keithhedger Sat 2 Oct 13:40:05 BST 2021 kdhedger68713@gmail.com

NORMAL="\e[0m"
RED="\e[1;31m"
GREEN="\e[1;32m"

ARGC=${#}

STATUS=${STATUS:-"progress"}
WRITEBYTES=${WRITEBYTES:-128M}

INFILE="${1}"
OUTFILE="${2}"

sudo -Kk

printHelp ()
{
	echo "Usage:"
	echo "SaferDD INPUTFILE OUTPUTFILE"
	echo "ENV Vars:"
	echo "STATUS=[none|noxfer|progress] Default=progress"
	echo "WRITEBYTES=BYTES Default=128M"
	echo
}

printNoArgs ()
{
	echo -e "${RED}Need two args ...${NORMAL}"
	echo -e "${GREEN}Arg 1=${INFILE}"
	echo -e "${RED}Arg 2=${OUTFILE}${NORMAL}"
	echo -e "${RED}Exiting ...${NORMAL}"
	exit 100
}

checkArgs ()
{
	infile=${INFILE}
	outfile=${OUTFILE}

	if [[ ! -e $infile ]];then
		echo -e "${RED}Input file  ${infile} MUST exist ...${NORMAL}"
		exit 100
	fi

	if [[ -d $outfile ]];then
		echo "${RED}Output $outfile is a folder"
		echo -e "Exiting ...${NORMAL}"
		exit 100
	fi

	if [[ -e $outfile ]];then
		if [[ $(realpath $infile) = $(realpath $outfile) ]];then
			echo -e "${RED}Input ${infile} is the same as Output ${outfile}"
			echo -e "Exiting ...${NORMAL}"
			exit 100
		fi
	fi
}

if [ ${ARGC} -lt 2 ];then
	printHelp
	printNoArgs
	exit 100
fi

checkArgs

echo -e "Input file=${GREEN}${INFILE}${NORMAL}"
echo -e "Output file=${RED}${OUTFILE}${NORMAL}"

if [[ -e "$OUTFILE" ]];then
	echo -e "${RED}!!!WARNINIG!!!\n${NORMAL}Output file ${GREEN}'${OUTFILE}'${NORMAL} ${RED}WILL${NORMAL} be overwritten!"
fi

echo "Using command:"
echo "sudo dd status=${STATUS} bs=${WRITEBYTES} if=$INFILE of=$OUTFILE"

DD=$(which dd)
read -p "run this command ? [N/y] "
if [[ ${REPLY^^} = "Y" ]];then
	sudo $DD status=${STATUS} bs=${WRITEBYTES} if=$INFILE of=$OUTFILE
fi
	







