#!/bin/bash -e

HAYSTACK="100abcd:::abcd:::abcd"
PART="ABBA"
FIND="abcd"
POS=5
LEN=4
echo $HAYSTACK $PART $FIND $LEN
##TODO nested slicing
##NEEDLE=${HAYSTACK//abc/${PART//"AB"/"ab"}}
#needs doing
NEEDLE="${HAYSTACK//${FIND}/$PART} xxx {rtret} \"XXX\" << {qwerty}  \"done\""
echo $HAYSTACK
echo $NEEDLE
echo ${#NEEDLE}

RESULT=${HAYSTACK:2}
echo $HAYSTACK
echo $RESULT
echo ${#RESULT}

RESULT=${HAYSTACK:${POS}}
echo $HAYSTACK
echo $RESULT
echo ${#RESULT}

RESULT=${HAYSTACK:${POS}:$LEN}
echo $HAYSTACK
echo $RESULT
echo ${#RESULT}
