#!/bin/bash -e

HAYSTACK="100abcd:::abcd:::abcd"
PART="ABBA"
FIND="abcd"
POS=5
LEN=4
echo $HAYSTACK $PART $FIND $LEN
##TODO nested slicing
##NEEDLE=${HAYSTACK//abc/${PART//"AB"/"ab"}}
#needs doing
#NEEDLE="${HAYSTACK//${FIND}/$PART} xxx {rtret} \"XXX\" << {qwerty}  \"done\""
echo $HAYSTACK
echo $NEEDLE
echo ${#NEEDLE}

RESULT=${HAYSTACK:2}
echo $HAYSTACK
echo $RESULT
echo ${#RESULT}

RESULT=${HAYSTACK:${POS}}
echo $HAYSTACK
echo $RESULT
echo ${#RESULT}

RESULT=${HAYSTACK:${POS}:$LEN}
echo $HAYSTACK
echo $RESULT
echo ${#RESULT}

avar="abcdef1.abcdfe2.abcdef3.abcdef4"
echo ${avar}
echo ${avar#*.abc}
echo ${avar##*.abc}
echo
echo ${avar%.abc*}
echo ${avar%%.abc*}

bvar=${avar%.abc*}

echo


APATH="/media/MediaStore/Music/Flacs/Music/Abba/Gold/01 Dancing Queen.flac"
echo ${APATH#*/Music/}
echo ${APATH##*/Music/}
echo ${APATH##*/}
echo ${APATH%.flac}

bvar=${avar%.abc*}
